import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ params: { lang },children}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <div>
          <Header />
          {children}

        </div>
      </body>
    </html>
  );
}
